# Generated by Django 3.1.2 on 2022-01-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCommand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandemployee',
            name='salary',
        ),
        migrations.AddField(
            model_name='commandemployee',
            name='region',
            field=models.CharField(choices=[('NA', 'North America'), ('EU', 'Europe')], default='NA', max_length=2),
            preserve_default=False,
        ),
    ]
