# Generated by Django 3.1.2 on 2022-01-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCommand', '0002_auto_20220114_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandemployee',
            name='moderator',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
