# Generated by Django 4.0.1 on 2022-01-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('student_surname', models.CharField(max_length=100)),
                ('rollnumber', models.CharField(max_length=100)),
            ],
        ),
    ]
